############# English navigation ##############

# main menu
[[main]]
name = "Etusivu"
url = "/"
weight = 1

[[main]]
name = "Yrityksille"
url = "/about"
weight = 2

#[[main]]
#name = "Vibes-passi"
#url = "/elements"
#weight = 3

[[main]]
name = "Yhteistyökumppanit"
url = "/#kumppanit"
weight = 4

#[[main]]
#name = "Yhteystiedot"
#url = "/yhteystiedot"
#weight = 5

#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "/blog"

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "/contact"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "/authors"

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"


# footer menu
#[[footer]]
#name = "Mikä on VIBEs?"
#url = "/tietoa"
#weight = 1
#[[footer]]
#name = "VIBEs-passi"
#url = "/passi"
#weight = 2
[[footer]]
name = "Yhteistyökumppanit"
url = "/#kummpanit"
weight = 2
[[footer]]
name = "Ota yhteyttä"
url = "mailto:vibes@jciouluntervaporvarit.fi"
weight = 3